# Generated by Django 3.2.4 on 2023-10-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_technical'),
    ]

    operations = [
        migrations.AddField(
            model_name='technical',
            name='work',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='内容'),
        ),
    ]
