# Generated by Django 3.2.4 on 2023-10-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_technical_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='githubimage',
            field=models.ImageField(default='default_image.jpg', upload_to='images', verbose_name='github画像'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitterimage',
            field=models.ImageField(default='default_image.jpg', upload_to='images', verbose_name='ツイッター画像'),
        ),
    ]
