# Generated by Django 3.2.4 on 2023-10-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20231013_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wantedly',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='wantedly'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wantedlyimage',
            field=models.ImageField(default='default_image.jpg', upload_to='images', verbose_name='github画像'),
        ),
    ]
