# Generated by Django 3.2.4 on 2023-10-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231013_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wantedlyimage',
            field=models.ImageField(default='default_image.jpg', upload_to='images', verbose_name='wantedly画像'),
        ),
    ]
